language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

addons:
  apt:
    packages:
    - dnsutils

before_script:
  - composer install --no-interaction -o

script:
  - vendor/bin/phpunit

branches:
  only:
    - master